### ISSUE TITLE
1.7 version

### ISSUE THREAD

**Issue by PatriceVigier** [krzysztofgal/psImageRegenCLI#1]
Can you update it to 1.7 version and higher?

**Comment by krzysztofgal** [comment]
:-1: I don't have the time or reason to do it. Maybe next year as long as I need it.

**Comment by krzysztofgal** [comment]
Obecnie używam Thirtybees i w tym oprogramowaniu regeneracja zdjęć nie jest problemem.

**Comment by krzysztofgal** [comment]
I currently use Thirtybees and in this software regeneration of photos is not a problem.
